export { Footer } from "@/components/Footer"
export { Header } from "@/components/Header"
export { Hero } from "@/components/Hero"
export { HeroPartners } from "@/components/HeroPartners"
export { HowItWorks } from "@/components/HowItWorks"
export { Layout } from "@/components/Layout"
export { MobileHeader } from "@/components/MobileHeader"
export { NavigationMenuDemo as NavigationMenu } from '@/components/NavigationMenu'
export { PopBenefits } from "@/components/PopBenefits"
export { POPCard } from "@/components/POPCard"
export { POPInNumbers } from "@/components/POPInNumbers"